/* Silph offline cache — generated by scripts/emit_offline.py. Do not hand-edit. */
const CACHE = "silph-2026-08-13-oracle-f458ede19fc6";
const PRECACHE = [
  "./",
  "index.html",
  "scan.html",
  "set-macro.html",
  "mid-sleeve-leftovers.html",
  "chase-sleeve-leftovers.html",
  "show-deals.html",
  "commons-vs-uncommons.html",
  "primes.html",
  "buying.html",
  "listings-watch.html",
  "hunt.html",
  "img/buying-examples.svg",
  "img/buying-flow.svg",
  "img/buying-how.svg",
  "img/reverse/bw5-89.jpg",
  "img/reverse/dp3-27.jpg",
  "img/reverse/dp6-39.jpg",
  "img/reverse/dp6-45.jpg",
  "img/reverse/ex16-44.jpg",
  "img/reverse/ex16-88.jpg",
  "img/reverse/ex2-56.jpg",
  "img/reverse/ex2-91.jpg",
  "img/reverse/ex3-52.jpg",
  "img/reverse/hgss4-6.jpg",
  "img/reverse/pl1-14.jpg",
  "img/reverse/pl4-72.jpg",
  "data/cards.csv",
  "data/cards.json",
  "data/cu-detail.json",
  "data/meta.json",
  "data/reverse-images.json",
  "data/sets.json",
  "manifest.webmanifest"
];
const IMG_HOSTS = ["images.pokemontcg.io", "storage.googleapis.com"];

self.addEventListener("install", (e) => {
  // addAll is atomic — one 404 would leave the whole thing uncached, and a
  // convention floor is the worst place to discover that. Cache individually.
  e.waitUntil(caches.open(CACHE).then((c) =>
    Promise.all(PRECACHE.map((u) => c.add(u).catch(() => null)))
  ).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  // A new freeze means a new cache name; drop every older one so the phone
  // cannot keep serving last week's prices.
  e.waitUntil(caches.keys().then((keys) =>
    Promise.all(keys.filter((k) => k.startsWith("silph-") && k !== CACHE)
                    .map((k) => caches.delete(k)))
  ).then(() => self.clients.claim()));
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;
  const isImg = IMG_HOSTS.includes(url.hostname);
  if (!sameOrigin && !isImg) return;

  if (isImg) {
    // Card art: cache-first, and keep whatever we managed to fetch once.
    //
    // A cross-origin <img> is a no-cors request, so the response is OPAQUE and
    // its status is 0, not 200. Gating on `status === 200` therefore cached
    // nothing at all — every image was refetched from the network forever and
    // none survived going offline. Accept opaque responses explicitly.
    e.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      const keepable = res && (res.status === 200 || res.type === "opaque");
      if (keepable) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
      }
      return res;
    }).catch(() => hit)));
    return;
  }

  // Documents: cache-first so a flaky hall network cannot stall the page, with a
  // background refresh so a reload on real wifi picks up a new freeze.
  e.respondWith(caches.match(req).then((hit) => {
    const net = fetch(req).then((res) => {
      if (res && res.status === 200) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }).catch(() => hit);
    return hit || net;
  }));
});
